/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static View.Login.username;
import java.util.Comparator;
import java.util.PriorityQueue;
import java.util.TreeSet;
import javaswing.History;
import javaswing.Stock;
import javaswing.TypeStock;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class MailBox extends javax.swing.JFrame {

    /**
     * Creates new form MailBox
     */
    private static DefaultTableModel defaultTableModel = new DefaultTableModel();
    public MailBox() {
        initComponents();
        this.AddItemComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_BackHome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ListMailBox = new javax.swing.JTable();
        cb_TypeStock = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_BackHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_BackHome.setText("Back Home");
        btn_BackHome.setFocusTraversalPolicyProvider(true);
        btn_BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackHomeActionPerformed(evt);
            }
        });

        tb_ListMailBox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_ListMailBox);

        cb_TypeStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TypeStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_BackHome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_TypeStock, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_BackHome)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_TypeStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_btn_BackHomeActionPerformed

    private void cb_TypeStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TypeStockActionPerformed
        // TODO add your handling code here:
        String item = (String)cb_TypeStock.getSelectedItem();
        defaultTableModel.setColumnCount(0);
        defaultTableModel.setRowCount(0);
        this.AddTableListHistory(item);
    }//GEN-LAST:event_cb_TypeStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MailBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MailBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MailBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MailBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MailBox().setVisible(true);
            }
        });
    }
    private void AddItemComboBox(){
        cb_TypeStock.addItem("All");
        TypeStock st = new TypeStock();
        TreeSet<String> set = new TreeSet<>();
        set = st.TreeSetSQLTypeStock();
        for(String name : set){
           cb_TypeStock.addItem(name); 
        }
    }
    private void AddTableListHistory(String s){
        PriorityQueue<History> queue = new PriorityQueue<>(new CompareNameStock1()); 
        queue = new History().GetPriorityQueueMailBox();
        tb_ListMailBox.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Name Stock");
        defaultTableModel.addColumn("Price");
        defaultTableModel.addColumn("Quantity");
        defaultTableModel.addColumn("Seller");
        while(queue.size() > 0){
            History a = queue.poll();
            if(a.getUsername().equalsIgnoreCase(username)){
                if(s.equalsIgnoreCase("All")){
                    String data1[] = new String[4];
                    data1[0] = a.getNameStock();
                    data1[1] = String.valueOf(a.getPrice());
                    data1[2] = String.valueOf(a.getQuantity());
                    data1[3] = a.getSeller();
                    defaultTableModel.addRow(data1);  
                }
                if(s.equalsIgnoreCase(a.getNameStock())){
                    String data1[] = new String[4];
                    data1[0] = a.getNameStock();
                    data1[1] = String.valueOf(a.getPrice());
                    data1[2] = String.valueOf(a.getQuantity());
                    data1[3] = a.getSeller();
                    defaultTableModel.addRow(data1);    
                }
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BackHome;
    private javax.swing.JComboBox<String> cb_TypeStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_ListMailBox;
    // End of variables declaration//GEN-END:variables
}
class CompareNameStock1 implements Comparator<History>{
    @Override
    public int compare(History s1 , History s2){
       return s1.getNameStock().compareTo(s2.getNameStock());
    }
}